version: '3.8'

services:
  sms-app:
    # Tự động build từ code hiện tại
    build: .
    container_name: sms
    
    # Mở cổng web
    ports:
      - "8501:8501"
    
    # Kết nối Database trên máy bạn
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=221106
      - DB_NAME=gr2
    
    volumes:
      - .:/app