version: '3.8'

services:
  sms-app:
    # Tự động build từ code hiện tại
    build: .
    container_name: sms
    
    # Mở cổng web
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=221106
      - DB_NAME=gr2
    
    volumes:
      - .:/app